import editAddress from "../../../support/pageObject/editAddress"
const editAddressdata = require('../../../fixtures/editAddressdata.json')

describe('Edit Address', () => {
    beforeEach(() => {
      cy.visit('')
    })  

    it('Success Edit Address', () => {
        cy.contains('Sign In').click()
        cy.get(editAddress.email).type(editAddressdata["email"])
        cy.get(editAddress.pw).type(editAddressdata["pw"])
        editAddress.clickSignIn()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click({force: true})
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
        cy.get('.box-billing-address > .box-actions > .action > span').click()
        cy.get('#telephone').clear().type(editAddressdata["nohp"])
        cy.get('#street_1').clear().type(editAddressdata["jalan1"])
        cy.get('#street_2').clear().type(editAddressdata["jalan2"])
        cy.get('#street_3').clear().type(editAddressdata["jalan3"])
        cy.get('#city').clear().type(editAddressdata["kota"])
        cy.get('#region_id').select('Hawaii')
        cy.get('#zip').clear().type(editAddressdata["pos"])
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click({force: true})
        cy.get('.message-success > div').should('contain.text', 'You saved the address')
    })
    it('form input pos empty', () => {
      cy.contains('Sign In').click()
      cy.get(editAddress.email).type(editAddressdata["email"])
      cy.get(editAddress.pw).type(editAddressdata["pw"])
      editAddress.clickSignIn()
      cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click({force: true})
      cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
      cy.get('.box-billing-address > .box-actions > .action > span').click()
      cy.get('#telephone').clear().type(editAddressdata["nohp"])
      cy.get('#street_1').clear().type(editAddressdata["jalan1"])
      cy.get('#street_2').clear().type(editAddressdata["jalan2"])
      cy.get('#street_3').clear().type(editAddressdata["jalan3"])
      cy.get('#city').clear().type(editAddressdata["kota"])
      cy.get('#region_id').select('Hawaii')
      cy.get('#zip').clear().type(editAddressdata["pos"])
      cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click({force: true})
      })
      it('Success Edit but no telpon incorrect', () => {
        cy.contains('Sign In').click()
        cy.get(editAddress.email).type(editAddressdata["email"])
        cy.get(editAddress.pw).type(editAddressdata["pw"])
        editAddress.clickSignIn()
        cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click({force: true})
        cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click({force: true})
        cy.get('.box-billing-address > .box-actions > .action > span').click()
        cy.get('#telephone').clear().type(editAddressdata["nohpincorrect"])
        cy.get('#street_1').clear().type(editAddressdata["jalan1"])
        cy.get('#street_2').clear().type(editAddressdata["jalan2"])
        cy.get('#street_3').clear().type(editAddressdata["jalan3"])
        cy.get('#city').clear().type(editAddressdata["kota"])
        cy.get('#region_id').select('Hawaii')
        cy.get('#zip').clear().type(editAddressdata["pos"])
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click({force: true})
        cy.get('.base').should('contain.text', 'Address Book')
        })
})